name: Check Pull Request Changes

on:
  pull_request:
    types: [opened, synchronize, reopened]

# token needs some additional permissions to be able to add a comment to the PR
# and read all PR data
# permissions can vary depending on the metrics you want to use and org settings
permissions:
  contents: read
  checks: read
  pull-requests: write
  repository-projects: read
  actions: read
  
jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run script to check PR changes
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python check_changes.py
        