---
    name: Quality Gate
    on:
        pull_request:
            branches:
                - main
        workflow_dispatch:
    
    jobs:
        full-build-test:
            runs-on:
                - ubuntu-latest
            steps:
                - name: Checkout
                  uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
                  with:
                    fetch-depth: 0
                - name: Get list of changed files
                  id: changed-files
                  run: |
                    files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
                    changedFiles="${files//$'\n'/,}"
                    echo $changedFiles
                    echo "changedFiles=$changedFiles" >> $GITHUB_ENV
                    IFS=',' read -ra file_array <<< "$changedFiles"
                    for file in "${file_array[@]}"; do
                        echo "$file"
                    done
                - name: Call Cmake with multiple targets
                  run: |
                    changedFiles_for_cmake="${changedFiles//$','/' '}"
                    echo "cmake --build . --target $changedFiles_for_cmake"
                - name: Call ctest for every target
                  run: |
                    changedFiles_for_cmake="${changedFiles//$','/' '}"
                    IFS=',' read -ra file_array <<< "$changedFiles"
                    for file in "${file_array[@]}"; do
                        echo "ctest --preset=default -j `nproc` -VV -R \"^$file(\..*)?\.unit\.all$\""
                    done


